//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRAMKI
    {
        public decimal Id_Strzelec { get; set; }
        public int Id_gospo { get; set; }
        public int Id_gosc { get; set; }
        public decimal Id_pilkarze { get; set; }
        public decimal PIL_Id_pilkarze { get; set; }
        public Nullable<System.TimeSpan> Czas_bramki { get; set; }
    
        public virtual PILKARZE PILKARZE { get; set; }
        public virtual SPOTKANIA SPOTKANIA { get; set; }
        public virtual PILKARZE PILKARZE1 { get; set; }
    }
}
