//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EkstraklasaEntities : DbContext
    {
        public EkstraklasaEntities()
            : base("name=EkstraklasaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRAMKI> BRAMKI { get; set; }
        public virtual DbSet<DRUZYNY> DRUZYNY { get; set; }
        public virtual DbSet<KARTKI> KARTKI { get; set; }
        public virtual DbSet<PILKARZE> PILKARZE { get; set; }
        public virtual DbSet<SEDZIOWIE> SEDZIOWIE { get; set; }
        public virtual DbSet<SPOTKANIA> SPOTKANIA { get; set; }
        public virtual DbSet<TRENERZY> TRENERZY { get; set; }
    }
}
