//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARTKI
    {
        public decimal Id_kartki { get; set; }
        public decimal Id_pilkarze { get; set; }
        public Nullable<decimal> Id_sed { get; set; }
        public Nullable<int> Id_gospo { get; set; }
        public Nullable<int> Id_gosc { get; set; }
        public Nullable<int> Rodzaj_kartki { get; set; }
        public string Nazwa_sed { get; set; }
        public string Nazwa_pilk { get; set; }
    
        public virtual PILKARZE PILKARZE { get; set; }
        public virtual SEDZIOWIE SEDZIOWIE { get; set; }
        public virtual SPOTKANIA SPOTKANIA { get; set; }
    }
}
