//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDZIOWIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEDZIOWIE()
        {
            this.KARTKI = new HashSet<KARTKI>();
        }
    
        public decimal Id_sed { get; set; }
        public Nullable<int> Id_gospo { get; set; }
        public Nullable<int> Id_gosc { get; set; }
        public string Imie_sed { get; set; }
        public string Nazwisko_sed { get; set; }
        public Nullable<int> Wiek_sed { get; set; }
        public Nullable<int> Ilosc_wydanych_kartek { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARTKI> KARTKI { get; set; }
        public virtual SPOTKANIA SPOTKANIA { get; set; }
    }
}
