//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRENERZY
    {
        public decimal Id_tren { get; set; }
        public Nullable<decimal> Id_druz { get; set; }
        public string Imie_tren { get; set; }
        public string Nazwisko_tren { get; set; }
        public string Nazwa_druz_tren { get; set; }
        public Nullable<int> Wiek_tren { get; set; }
    
        public virtual DRUZYNY DRUZYNY { get; set; }
    }
}
